viewer = evince
document_name = document
font = Georgia
fontsize = 12pt
margin = 2.5cm

# images generated by Make (not static images)
images = 


.PHONY: all show clean

all: $(document_name).pdf

show: $(document_name).pdf
	$(viewer) $< 2>&1>/dev/null &

clean:
	rm -f $(document_name).pdf $(images)

$(document_name).pdf: $(document_name).md $(document_name).latex refs.bib $(images)
	pandoc -o $@ -V geometry:margin=$(margin) \
	--variable fontsize=$(fontsize) \
	--variable mainfont="$(font)" --latex-engine=xelatex \
	--bibliography refs.bib --csl csl/default.csl \
	--template $(document_name).latex $<
